### ISSUE TITLE
How to use Redom jsx pragma

### ISSUE THREAD

**Issue by IFaniry** [tomerigal/babel-plugin-transform-redom-jsx#152]
Hello,

How do you set `compilerOptions.jsx` and `compilerOptions.jsxImportSource` as in the following link in order to use Redom JSX with Deno Fresh?

[https://deno.com/blog/fresh-1.1#automatic-jsx](https://deno.com/blog/fresh-1.1#automatic-jsx)

Thank you

**Comment by tomerigal** [comment]
Hello @IFaniry. 
I haven't used deno/fresh myself, but if you're referring to tsconfig values, I believe the following might be in the right direction:

```{
  "compilerOptions": {
    "jsx": "react",
    "jsxImportSource": "redom",
    "jsxFactory": "redom.el"
  }
}
```
