### ISSUE TITLE
Create custom components directly, not using el()

### ISSUE THREAD

**Issue by sc0ty** [tomerigal/babel-plugin-transform-redom-jsx#35]
When writing custom components like this:
```javascript
class Test {
  constructor(attrs, children) {
    <p this='el' style={{color: attrs.color}}><b>{children}</b></p>
  }
}
```
And instantiating it:
```html
<Test color='red'>Hello world</Test>
```
We will get DOM object like that:
```html
<p color="red"><b style="color: red"></b>Hello world</p>
```

That's because parameters passed to `el()` are added to `this.el` of custom component. I was [asking redom](https://github.com/redom/redom/issues/192) if this is expected behaviour and it is.

Fixing this would require calling el() like this:
```javascript
el(new Test({color: red}, text("Hello world")));
```
instead of:
```javascript
el(Test, {color: red}, text("Hello world"));
```
Of course non-custom components should be constructed like before. I think it could be done by checking if first argument of el() is typeof "object".

**Comment by tomerigal** [comment]
Thank you for the informative report!
I'll look into it in the upcoming week.

**Comment by tomerigal** [comment]
@sc0ty upgrade to v3.0.0 👍
