### ISSUE TITLE
Webpack "Cannot find module 'babel-plugin-redom-jsx'"

### ISSUE THREAD

**Issue by jcuenod** [tomerigal/babel-plugin-transform-redom-jsx#38]
I'm setting up a new environment with redom and this "jsx" transformation with webpack 4 and babel 7. When I run webpack, though, I get this error:

    ERROR in ./src/index.js
    Module build failed (from ./node_modules/babel-loader/lib/index.js):
    Error: Cannot find module 'babel-plugin-redom-jsx'

My `.babelrc` is modified to follow `README.md`:

```
{
    "presets": ["@babel/preset-env"],
    "plugins": [
        "babel-plugin-redom-jsx",
        ["transform-react-jsx", {
            "pragma": "el"
        }]
    ]
}
```

Note that with only the preset in my `.babelrc` webpack runs fine.

**Comment by tomerigal** [comment]
There's a typo in the README .
The name of the module should be "babel-plugin-transform-redom-jsx".
Thanks :)
