### ISSUE TITLE
How to create list ?

### ISSUE THREAD

**Issue by lionel-bijaoui** [tomerigal/babel-plugin-transform-redom-jsx#6]
I'm trying to build a simple list component, and I don't know how to update it.

```jsx
import { el } from 'redom';

export default class List {
  constructor({ listInput }, text) {
    let listItems = [];
    for (let i = 0; i < listInput.length; i++) {
      listItems.push(
        <li>
          {i} - {listInput[i]}
        </li>
      );
    }
    <ul this="el">{listItems}</ul>;
  }
  update() {
    // how do I update if listInput change ?
  }
}
```
Should I use the `list` method from REDOM ? 
How do you mix JSX and REDOM Hyperscript ?

Thank you for your help !

**Comment by tomerigal** [comment]
Hi @lionel-bijaoui 
Yes you probably want to use `list` method from RE:DOM for component lifecycle and cache.
Another method you can use is [setChildren](https://redom.js.org/documentation/#set-children), good when you have a different elements.

Example using list:
```js
class Td {
  constructor () {
    this.el = <td />; // or <td this="el" />
  }
  update (data) {
    this.el.textContent = data;
  }
}

class CustomTable {
  constructor () {
    this.el = <table>{this.items = list('tr', Td)}</table>;
  }
  update (data) {
    this.items.update(["hello world"]);
  }
}
```

Thankyou :-)

**Comment by lionel-bijaoui** [comment]
Thank you !
